### ISSUE TITLE
urllib3 or chardet outdated

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#12]
Hi !

Since the last upgrade of my System (I'm on Arch Linux) I've the following error on the first request (not the following): 

```
"../rest_request_with_vim.roast" 158L, 3908C
Error detected while processing /home/julioprayer/.vim/plugged/roast.vim/autoload/roast.vim:
line   15:
/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

It seems that the Roast Plugin continue to work without problems… 

My `python --version`: 3.7.3

Thanks in advance !

**Comment by JulioJu** [comment]
Furthermore sometimes I have the following error:
```
Error detected while processing function roast#run:
line    1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 284, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: HTTP/1.1 20 ^M
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in r
```

**Comment by sharat87** [comment]
I think the problem is with having multiple installs of the requests library. Can you get me the output of the following python code snippet from your system please?

```python
import requests, urllib3, chardet
print('requests', requests.__version__)
print('urllib3', urllib3.__version__)
print('chardet', chardet.__version__)
```

Thanks!

**Comment by JulioJu** [comment]
Ok thanks for your answer. Actually this error doesn't occur anymore.
