### ISSUE TITLE
jinja2 not found

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#26]
Hi !

When I open a file with an extension `.roast` I have the following error:

```
"/tmp/essai.roast" 2L, 22C
Error detected while processing /home/julioprayer/.vim/plugged/roast.vim/ftplugin/roast.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/julioprayer/.vim/plugged/roast.vim/python3/roast.py", line 21, in <module>
    import roast_api
  File "/home/julioprayer/.vim/plugged/roast.vim/python3/roast_api.py", line 13, in <module>
    from jinja2 import Template
ModuleNotFoundError: No module named 'jinja2'
Error detected while processing /home/julioprayer/.vim/plugged/roast.vim/after/ftplugin/roast.vim:
line    9:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'roast' is not defined
```

`sudo pip install jinja2` fixes the problem. Maybe, you could says that this plugin requires `jinja2` and give this tip in the README.md , for those that don't know the `pip` util?

**Comment by sharat87** [comment]
Just pushed fix for this as well as a note in the docs. Thanks!
