### ISSUE TITLE
No such highlight group name: RoastCurrentFailure

### ISSUE THREAD

**Issue by JulioJu** [sharat87/roast.vim#4]
Hi !

Thanks for your plugin!

When the server send the following response
```
=== Response Headers ===
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
Date: Thu, 11 Apr 2019 15:37:52 GMT
Connection: keep-alive
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
Content-Type: application/problem+json


=== Request Headers ===
Accept: application/json, text/plain
Content-Type: application/json
Referer: http://localhost:9000
Accept-Encoding: identity
```

We have the following red error message in the cmd line of Vim
```
Error detected while processing function roast#run:                                                                                                                                 
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/julioprayer/.vim/plugged/roast.vim/python3/roast.py", line 40, in run
    highlight_line_text('RoastCurrentSuccess' if response.ok else 'RoastCurrentFailure')
  File "/home/julioprayer/.vim/plugged/roast.vim/python3/roast.py", line 98, in highlight_line_text
    vim.current.buffer.vars['_roast_match_id'] = vim.eval(f"matchadd('{group}', '\\V{vim.current.line}')")
vim.error: Vim:E28: No such highlight group name: RoastCurrentFailure
```
When we press Enter, this message disappears and Roast works well. 

I suppose the problem is with `Content-Type: application/problem+json`?

Thanks in advance !

**Comment by JulioJu** [comment]
An other example is simply to use
```vim
POST https://httpbin.org/forms/post << END
{{
    "toto": 1,
}}
END
```

httpbin sent error 405 and an error message is displayed.

**Comment by sharat87** [comment]
Hi Julio! Thanks for your report. I tried the following requests but am unable to see the error you pasted. However, after some digging through, I think I found and fixed the problem. Please test the updated version and let me know what you see.

Thanks.

**Comment by JulioJu** [comment]
Thanks @sharat87 , so cool ! So cool plugin !
